### ISSUE TITLE
ERROR - CVE not found.

### ISSUE THREAD

**Issue by majidmc2** [andreafioraldi/cve_searchsploit#3]
Hi 
I installed this tool but when I used it, I got this error:
`ERROR - CVE not found.`

My command is:
`$ cve_searchsploit 2019-8045`

**Comment by andreafioraldi** [comment]
maybe cause the CVE ID format is CVE-year-id? porcodio, this script is a few lines of code, open it and read.

**Comment by thebabush** [comment]
This project really needs a CoC because it's very t*xic.

**Comment by CarloMara** [comment]
@thebabush I use this code on a daily basis and I would love if the project would have a CoC.

@andreafioraldi count me in if you need help writing it.

Love to all,
Carlo

**Comment by andreafioraldi** [comment]
This project already have a CoC (the Call of Cthulhu) and, even better, a
CoCk. 8=========D

Il lun 11 mag 2020, 17:45 Carlo Maragno <notifications@github.com> ha
scritto:
